//This c++ code is generated by PictoBlox

//Included Libraries
#define LILYGO_WATCH_2019_WITH_TOUCH
#include <LilyGoWatch.h>

//MACROS are defined here
TTGOClass *ttgo;

void setup() {
  //put your setup code here, to run once:
  ttgo = TTGOClass::getWatch();
  ttgo->begin();
  ttgo->openBL();
  ttgo->tft->init(TFT_BLACK);
  ttgo->tft->setRotation(0);
  pinMode(26, OUTPUT);
  
  
  ttgo->tft->setRotation(0);
  ttgo->tft->setTextColor(63330, 0);
  ttgo->tft->setTextSize(2);
  ttgo->tft->fillScreen(0);
}

void loop() {
  //put your main code here, to run repeatedly:
  
  
  digitalWrite(26, true);
  ttgo->tft->setCursor(10, 100);
  ttgo->tft->print("Relay On  ");
  delay(3 * 1000);
  digitalWrite(26, false);
  ttgo->tft->setCursor(10, 100);
  ttgo->tft->print("Relay Off");
  delay(3 * 1000);
}
