//This c++ code is generated by PictoBlox

//Included Libraries
#define LILYGO_WATCH_2019_WITH_TOUCH
#include <LilyGoWatch.h>

//MACROS are defined here
TTGOClass *ttgo;

void setup() {
  //put your setup code here, to run once:
  ttgo = TTGOClass::getWatch();
  ttgo->begin();
  ttgo->openBL();
  ttgo->tft->init(TFT_BLACK);
  ttgo->tft->setRotation(0);
  pinMode(25, INPUT);
  
  
  ttgo->tft->setRotation(0);
  ttgo->tft->fillScreen(0);
  ttgo->tft->setTextColor(65318, 0);
  ttgo->tft->setTextSize(2);
}

void loop() {
  //put your main code here, to run repeatedly:
  
  
  if(digitalRead(25)) {
    ttgo->tft->fillScreen(0);
  }
  else {
    ttgo->tft->setCursor(10, 100);
    ttgo->tft->print("Button Pressed!");
    delay(1 * 1000);
  }
}
