//This c++ code is generated by PictoBlox

//Included Libraries
#define LILYGO_WATCH_2019_WITH_TOUCH
#include <LilyGoWatch.h>
#include <Adafruit_NeoPixel.h>

//MACROS are defined here
TTGOClass *ttgo;
TFT_eSPI *tft;
Adafruit_NeoPixel Strip_1 = Adafruit_NeoPixel(4, 25, NEO_GRB + NEO_KHZ800);

void setup() {
  //put your setup code here, to run once:
  ttgo = TTGOClass::getWatch();
  ttgo->begin();
  ttgo->openBL();
  ttgo->tft->init(TFT_BLACK);
  ttgo->tft->setRotation(0);
  Strip_1.begin();
   Strip_1.show();
  
  
  ttgo->tft->setRotation(0);
  ttgo->tft->setTextColor(63330, 0);
  ttgo->tft->setTextSize(2);
  ttgo->tft->fillScreen(0);
  ttgo->tft->print("WS2812_RGB Rainbow");
}

void loop() {
  //put your main code here, to run repeatedly:
  
  
  Strip_1.pattern2(1, 0.05*1000);
}
